# Generated by Django 4.1.13 on 2025-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_assessments',
            name='assessment_completion_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='students_assessments',
            name='assessment_overall_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='students_assessments',
            name='assessment_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='students_assessments',
            name='assessment_week_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
