# Generated by Django 4.1.13 on 2025-03-11 04:15

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_details',
            name='student_question_details',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
