# Generated by Django 4.1.13 on 2025-03-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_practice_coding_ans',
            new_name='student_practice_coding_answers',
        ),
    ]
