# Generated by Django 4.1.13 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogs',
            name='Occurred_time',
            field=models.DateTimeField(),
        ),
    ]
