# Generated by Django 4.1.13 on 2025-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_test_questions',
            name='practice_completion_time',
        ),
        migrations.RemoveField(
            model_name='student_test_questions',
            name='practice_max_score',
        ),
        migrations.RemoveField(
            model_name='student_test_questions',
            name='practice_score_secured',
        ),
        migrations.RemoveField(
            model_name='student_test_questions',
            name='practice_week_number',
        ),
        migrations.AddField(
            model_name='student_test_questions',
            name='completion_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='student_test_questions',
            name='max_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student_test_questions',
            name='score_secured',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student_test_questions',
            name='test_id',
            field=models.CharField(default='Test11', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_test_questions',
            name='week_number',
            field=models.IntegerField(default=0),
        ),
    ]
