# Generated by Django 4.1.13 on 2025-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_practice_coding_ans',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
