# Generated by Django 4.1.13 on 2025-03-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0002_rename_student_practice_coding_ans_student_practice_coding_answers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_practice_coding_answers',
            table='student_practice_coding_answers',
        ),
    ]
