# Generated by Django 4.1.13 on 2025-03-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0002_student_practice_coding_ans_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_practice_coding_ans',
            name='Attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_assessments',
            name='assessment_status',
            field=models.CharField(default='UPCOMMING', max_length=20),
            preserve_default=False,
        ),
    ]
