# Generated by Django 4.1.13 on 2025-04-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0002_alter_students_assessments_assessment_completion_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students_assessments',
        ),
    ]
