# Generated by Django 4.1.13 on 2025-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Mongodb_App', '0003_alter_student_practice_coding_answers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_practice_coding_answers',
            name='question_done_at',
            field=models.CharField(default='practice', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_practicemcq_answers',
            name='question_done_at',
            field=models.CharField(default='practice', max_length=20),
            preserve_default=False,
        ),
    ]
