# Generated by Django 4.1.13 on 2025-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_plan_details',
            name='content_type',
            field=models.CharField(default='study', max_length=20),
            preserve_default=False,
        ),
    ]
