# Generated by Django 4.1.13 on 2025-05-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='saturday_holiday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='batches',
            name='sunday_holiday',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
