# Generated by Django 4.1.13 on 2025-05-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_subjects',
            name='batch_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.batches'),
        ),
    ]
