# Generated by Django 4.1.13 on 2025-03-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_plane_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration_in_hours', models.IntegerField()),
                ('del_row', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_MSSQLdb_App.courses')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_MSSQLdb_App.subjects')),
            ],
            options={
                'db_table': 'course_plane_details',
            },
        ),
    ]
