# Generated by Django 4.1.13 on 2025-03-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0002_course_plane_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_plane_details',
            new_name='course_plan_details',
        ),
    ]
