# Generated by Django 4.1.13 on 2025-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0003_test_details_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_topics',
            name='sub_topic_name',
            field=models.CharField(max_length=100),
        ),
    ]
