# Generated by Django 4.1.13 on 2025-03-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0003_rename_course_plane_details_course_plan_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_plan_details',
            old_name='start_time',
            new_name='day_date',
        ),
    ]
