# Generated by Django 4.1.13 on 2025-03-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0003_students_info_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_topics',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-11 16:01:54.4165550 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='created_by',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sub_topics',
            name='sub_topic_alt_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
