# Generated by Django 4.1.13 on 2025-03-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0004_rename_start_time_course_plan_details_day_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course_plan_details',
            table='course_plan_details',
        ),
    ]
