# Generated by Django 4.1.13 on 2025-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0004_sub_topics_action_sub_topics_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tracks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
