# Generated by Django 4.1.13 on 2025-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0005_alter_course_plan_details_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='student_catogory',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MOON', 'MOON'), ('STAR', 'STAR')], default='STAR', max_length=20),
        ),
        migrations.AddField(
            model_name='students_info',
            name='student_college_rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='students_info',
            name='student_overall_rank',
            field=models.IntegerField(default=-1),
        ),
    ]
