# Generated by Django 4.1.13 on 2025-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0006_rename_trainer_firstname_trainers_trainer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='allocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students_info',
            name='student_course_starttime',
            field=models.DateTimeField(null=True),
        ),
    ]
