# Generated by Django 4.1.13 on 2025-03-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0007_students_info_allocate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('activity_status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('del_row', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
