# Generated by Django 4.1.13 on 2025-04-07 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0010_courses_existing_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_details',
            name='college_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.college_details'),
        ),
    ]
