# Generated by Django 4.1.13 on 2025-04-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0011_alter_branch_details_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_plan_details',
            name='batch_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.batches'),
        ),
    ]
