# Generated by Django 4.1.13 on 2025-04-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0015_college_details_college_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='access',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
