# Generated by Django 4.1.13 on 2025-04-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0016_admins_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college_details',
            name='college_type',
        ),
    ]
