# Generated by Django 4.1.13 on 2025-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0017_remove_college_details_college_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='suite_login_details',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('activity_status', models.CharField(max_length=20)),
                ('category', models.JSONField(blank=True, default=list)),
                ('reg_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('access', models.JSONField(blank=True, default=list)),
                ('del_row', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'suite_login_details',
            },
        ),
        migrations.DeleteModel(
            name='admins',
        ),
    ]
