# Generated by Django 4.1.13 on 2025-04-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0018_suite_login_details_delete_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suite_login_details',
            old_name='admin_email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='suite_login_details',
            old_name='admin_first_name',
            new_name='user_first_name',
        ),
        migrations.RenameField(
            model_name='suite_login_details',
            old_name='admin_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='suite_login_details',
            old_name='admin_last_name',
            new_name='user_last_name',
        ),
    ]
