# Generated by Django 4.1.13 on 2025-04-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0019_rename_admin_email_suite_login_details_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='test_date_and_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
