# Generated by Django 4.1.13 on 2025-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0020_alter_test_details_test_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
