# Generated by Django 4.1.13 on 2025-04-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0021_test_details_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_details',
            old_name='topics',
            new_name='topic_id',
        ),
    ]
