# Generated by Django 4.1.13 on 2025-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0022_rename_topics_test_details_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_details',
            name='tags',
        ),
        migrations.AddField(
            model_name='test_details',
            name='tagsq',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
