# Generated by Django 4.1.13 on 2025-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0024_rename_tagsq_test_details_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags2',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
