# Generated by Django 4.1.13 on 2025-04-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0026_remove_questions_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='tags2',
            new_name='tags',
        ),
    ]
