# Generated by Django 4.1.13 on 2025-04-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0028_alter_students_info_student_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_sections',
            name='section_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
