# Generated by Django 4.1.13 on 2025-04-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0029_test_sections_section_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test_sections',
            unique_together={('test_id', 'question_id')},
        ),
    ]
