# Generated by Django 4.1.13 on 2025-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0030_alter_test_sections_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='test_created_by',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
