# Generated by Django 4.1.13 on 2025-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0031_alter_test_details_test_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_info',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
