# Generated by Django 4.1.13 on 2025-04-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0032_alter_students_info_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=20)),
                ('assessment_status', models.CharField(choices=[('P', 'pending'), ('S', 'started'), ('C', 'completed')], max_length=20)),
                ('assessment_score_secured', models.FloatField()),
                ('assessment_max_score', models.FloatField()),
                ('assessment_week_number', models.IntegerField(default=None, null=True)),
                ('assessment_completion_time', models.DateTimeField(default=None, null=True)),
                ('assessment_rank', models.IntegerField(default=None, null=True)),
                ('assessment_overall_rank', models.IntegerField(default=None, null=True)),
                ('del_row', models.CharField(default='False', max_length=5)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.courses')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.students_info')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.subjects')),
                ('test_id', models.ForeignKey(db_column='Test_id', on_delete=django.db.models.deletion.CASCADE, to='LMS_MSSQLdb_App.test_details')),
            ],
            options={
                'db_table': 'students_assessments',
            },
        ),
    ]