# Generated by Django 4.1.13 on 2025-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0033_students_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_assessments',
            name='assessment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
