# Generated by Django 4.1.13 on 2025-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0034_alter_students_assessments_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='student_total_score',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
