# Generated by Django 4.1.13 on 2025-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0035_students_info_student_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='student_CGPA',
            field=models.FloatField(default=0.0),
        ),
    ]
