# Generated by Django 4.1.13 on 2025-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0036_students_info_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_assessments',
            name='student_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='students_assessments',
            name='student_test_completion_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
