# Generated by Django 4.1.13 on 2025-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0037_students_assessments_student_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_details',
            name='test_created_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
