# Generated by Django 4.1.13 on 2025-04-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0038_test_details_test_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_app_usage',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.students_info'),
        ),
        migrations.CreateModel(
            name='student_test_questions_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
                ('test_id', models.CharField(max_length=20)),
                ('score_secured', models.FloatField(default=0)),
                ('question_status', models.CharField(choices=[('Attempted', 'Attempted'), ('Pending', 'Pending'), ('Submitted', 'Submitted')], max_length=20)),
                ('max_score', models.FloatField(default=0)),
                ('week_number', models.IntegerField(default=0)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('del_row', models.CharField(default='False', max_length=5)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.questions')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.students_info')),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.subjects')),
            ],
            options={
                'db_table': 'student_test_questions_details',
            },
        ),
    ]
