# Generated by Django 4.1.13 on 2025-04-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0039_alter_student_app_usage_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_test_questions_details',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS_MSSQLdb_App.test_details'),
        ),
    ]
