# Generated by Django 4.1.13 on 2025-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0040_alter_student_test_questions_details_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_test_questions_details',
            name='week_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
