# Generated by Django 4.1.13 on 2025-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0041_alter_student_test_questions_details_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_assessments',
            name='student_test_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
