# Generated by Django 4.1.13 on 2025-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0042_students_assessments_student_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_test_questions_details',
            name='del_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students_assessments',
            name='del_row',
            field=models.BooleanField(default=False),
        ),
    ]
