# Generated by Django 4.1.13 on 2025-05-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_MSSQLdb_App', '0043_alter_student_test_questions_details_del_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_test_questions_details',
            name='student_answer',
            field=models.TextField(default=None, null=True),
        ),
    ]
